//! ANTICO Learning v3.1: 9-Stage Continuous Learning Loop Coordinator.
//! Manages L3 experience recording, promotion qualification, and Bayesian Beta distribution updates.

use antico_core::{
    AnticoError, MissionResult, PhysicalVerifierTrait, ScopedTask, Verdict,
};
use antico_execution::TaskDistributor;
use antico_memory::{
    AnticoMemoryEngine, KnowledgeEngineTrait, L3Experience, L4AuditRecord, MemoryContract,
    PromotionOutcome,
};
use antico_verification::AnticoPhysicalVerifier;
use serde::{Deserialize, Serialize};

/// Report generated by the 9-stage learning loop.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LearningReport {
    pub stage_reached: u8,
    pub verified_verdict: Verdict,
    pub experience_id: String,
    pub repeat_count: u32,
    pub promotion: Option<PromotionOutcome>,
    pub audit_id: String,
}

/// 9-Stage Learning Loop Coordinator.
pub struct LearningCoordinator {
    memory: AnticoMemoryEngine,
    verifier: AnticoPhysicalVerifier,
    distributor: TaskDistributor,
}

impl LearningCoordinator {
    pub fn new(
        memory: AnticoMemoryEngine,
        verifier: AnticoPhysicalVerifier,
        distributor: TaskDistributor,
    ) -> Self {
        Self {
            memory,
            verifier,
            distributor,
        }
    }

    /// Executes the full 9-stage learning pipeline on a mission result.
    pub async fn process_execution(
        &self,
        task: &ScopedTask,
        result: &MissionResult,
    ) -> Result<LearningReport, AnticoError> {
        // Stage 1: Ingest Result & Evidence
        let evidence_refs: Vec<String> = result.evidence.iter().map(|e| e.id.clone()).collect();

        // Stage 2: Independent Physical Verification Probe (§1.10)
        let verified_verdict = self.verifier.verify_evidence(task, &result.evidence).await?;
        let is_pass = verified_verdict.is_pass();

        // Stage 3: Update Bayesian Beta Distribution
        self.distributor
            .update_confidence(&result.agent_id, &task.required_capability, is_pass)
            .await;

        // Stage 4: Calculate repeat count from historical experiences
        let historical = self.memory.query_experiences(&task.mission_type).await;
        let repeat_count = historical
            .iter()
            .filter(|e| e.agent_used == result.agent_id.0 && e.verdict.is_pass())
            .count() as u32
            + if is_pass { 1 } else { 0 };

        let exp_id = format!("exp-{}-{}", task.id, result.completed_at_ms);
        let exp = L3Experience {
            id: exp_id.clone(),
            mission_type: task.mission_type.clone(),
            agent_used: result.agent_id.0.clone(),
            verdict: verified_verdict.clone(),
            repeat_count,
            is_promoted: false,
            evidence_refs,
            lesson: format!(
                "Execution by {} yielded verdict {:?}",
                result.agent_id, verified_verdict
            ),
            timestamp_ms: result.completed_at_ms,
        };

        // Record into L3 via lock-free queue
        self.memory.record_experience(exp).await?;

        // Stage 5 & 6: Evaluate Promotion Qualification & Promote (§120)
        let promotion = if is_pass && repeat_count >= 3 {
            self.memory.promote_experience(&exp_id).await.ok()
        } else {
            None
        };

        // Stage 7: Update TaskDistributor Routing (applied via Step 3 confidence updates)

        // Stage 8: Append Cryptographic L4 Audit Record (SHA256 chained)
        let audit_record = L4AuditRecord {
            id: format!("audit-{}", task.id),
            trace_id: format!("trace-{}", task.id),
            span_id: "span-learn".to_string(),
            action: "LEARNING_CYCLE_COMPLETE".to_string(),
            actor: "LearningCoordinator".to_string(),
            target: format!("Task:{}", task.id),
            status: if is_pass { "PASS".to_string() } else { "FAIL".to_string() },
            sha256_hash: String::new(),
            prev_hash: String::new(),
            timestamp_ms: result.completed_at_ms,
        };
        let audit_id = self.memory.append_audit(audit_record).await?;

        // Stage 9: Telemetry Emitted
        Ok(LearningReport {
            stage_reached: 9,
            verified_verdict,
            experience_id: exp_id,
            repeat_count,
            promotion,
            audit_id,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use antico_agents::AgentFleetRegistry;
    use antico_core::{AgentId, CapabilityId, Evidence, EvidenceKind, TaskId};

    #[tokio::test]
    async fn test_full_learning_cycle_promotes_on_third_pass() {
        let memory = AnticoMemoryEngine::new();
        let verifier = AnticoPhysicalVerifier::new();
        let registry = AgentFleetRegistry::new();
        let distributor = TaskDistributor::new(registry);

        let coordinator = LearningCoordinator::new(memory.clone(), verifier, distributor);

        let task = ScopedTask {
            id: TaskId("task-learn-01".to_string()),
            mission_type: "docker_deploy".to_string(),
            required_capability: CapabilityId("container_deployment".to_string()),
            payload: "run redis".to_string(),
            timeout_ms: 5000,
            memory_refs: vec![],
        };

        let make_result = |task_id: TaskId, exit_code: i32, completed_at_ms: u64| MissionResult {
            task_id: task_id.clone(),
            agent_id: AgentId("agent-docker-01".to_string()),
            verdict: if exit_code == 0 { Verdict::Pass } else { Verdict::Fail { reason: "err".to_string() } },
            evidence: vec![Evidence {
                id: format!("ev-{}", task_id),
                task_id,
                kind: EvidenceKind::ExitCode(exit_code),
                payload: "exit".to_string(),
                collected_at_ms: completed_at_ms,
            }],
            execution_time_ms: 20,
            completed_at_ms,
        };

        // Run 1
        let r1 = coordinator
            .process_execution(&task, &make_result(TaskId("t1".to_string()), 0, 1020))
            .await
            .unwrap();
        assert_eq!(r1.repeat_count, 1);
        assert!(r1.promotion.is_none());

        // Run 2
        let r2 = coordinator
            .process_execution(&task, &make_result(TaskId("t2".to_string()), 0, 1030))
            .await
            .unwrap();
        assert_eq!(r2.repeat_count, 2);
        assert!(r2.promotion.is_none());

        // Run 3: Meets threshold >= 3!
        let r3 = coordinator
            .process_execution(&task, &make_result(TaskId("t3".to_string()), 0, 1040))
            .await
            .unwrap();
        assert_eq!(r3.repeat_count, 3);
        assert!(r3.promotion.is_some());
    }
}
